input {
  file {
    path => "/data/audit.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} %{WORD:admin_user} %{WORD:action} %{DATA:object} %{WORD:status} %{IP:ip}"
    }
  }

  date {
    match => ["timestamp", "ISO8601"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "audit-logs-%{+YYYY.MM.dd}"
  }
}
