input {
  file {
    path => "/data/snort.alert"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => {
      "message" => "%{IP:src_ip}:%{INT:src_port} -> %{IP:dest_ip}:%{INT:dest_port} %{WORD:protocol} %{WORD:action} %{GREEDYDATA:rule}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "network-logs-%{+YYYY.MM.dd}"
  }
}
